name = "spino-gambinoavis-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambinoavis.fr"
HMAC_KEY = "8f08b756f5f4afc5c14b665df3e64a2828f7996f992ed78240d552e9e91809ce"
COOKIE_NAME = "n1h"
PLAY_PATH = "explore"
BUTTON_ID = "p3c284ac9ea77266f991654dfaeb67765"
GATE_SALT = "4c3e88f7ab6b5ac9"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "xydj"
CTA_SELECTOR = ".play-button"
